server:
  host: "0.0.0.0"
  port: 3000
  rateLimit:
    ttl: 60
    limit: 15
db:
  postgres:
    host: "localhost"
    port: 5432
    username: "postgres"
    password: 
    database: "tibu_auth"
    type: "postgres"
    migrationsRun: false
    maxQueryExecutionTime: 1000
  redis:
    host: "localhost"
    port: 6379
    password:
    username: